### ISSUE TITLE
Stylesheet for latest docs

### ISSUE THREAD

**Issue by rhdtownsend** [rhdtownsend/gyre#15]
The docs for the latest version on readthedocs (https://gyre.readthedocs.io/en/latest/) is missing all its formatting; could be a stylesheets problem.

**Comment by warrickball** [comment]
Huh. I just did a diff between the top of `master` and the `v6.0.1` tag and I didn't notice anything that looks like it'd have affected the style sheets. The `stable` docs look fine. Have you already tried telling ReadTheDocs to build again?

**Comment by warrickball** [comment]
The source for the `stable` and `latest` docs suggests the problem is these two lines missing near the beginning of the `latest` docs:
```html
<link rel="stylesheet" href="[_static/css/theme.css](view-source:https://gyre.readthedocs.io/en/stable/_static/css/theme.css)" type="text/css" />
<link rel="stylesheet" href="[_static/pygments.css](view-source:https://gyre.readthedocs.io/en/stable/_static/pygments.css)" type="text/css" />```

**Comment by warrickball** [comment]
This might be the same issue. The thread includes a fix.

https://github.com/readthedocs/sphinx_rtd_theme/issues/1240

**Comment by rhdtownsend** [comment]
Nice find. Added the suggested fix and it works.
