### ISSUE TITLE
Unrendered substitution-prompt blocks in documentation

### ISSUE THREAD

**Issue by jschwab** [rhdtownsend/gyre#9]
On the page https://gyre.readthedocs.io/en/latest/user-guide/example-walkthrough.html, under "Making a Place to Work" it doesn't show the commands.  Commands are missing other places in the page as well.

Looking at the source, `substitution-prompt` blocks don't seem to be showing up.

**Comment by rhdtownsend** [comment]
Looks like [sphinx-substitution-extensions](https://github.com/adamtheturtle/sphinx-substitution-extensions) made a code-breaking change to their syntax earlier this year. Fixed.
